services:
  kali:
    build: infra/docker/kali
    ports:
      - 3389:3389
      - 5902:5902
    environment:
      - PULSE_SERVER=/tmp/PulseServer
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/tmp/runtime-dir/
      - DISPLAY=:0
    networks:
      - my-network
    entrypoint: /bin/bash -c "/usr/lib/systemd/systemd-logind & /startvnc & /etc/init.d/xrdp restart & service dbus start & tail -f /dev/null"
  
networks:
  my-network:
    driver: bridge
